name: Cl

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Ngrok
      run: Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"

    - name: Extract Ngrok
      run: Expand-Archive -Path "ngrok.zip" -DestinationPath "$env:USERPROFILE\ngrok"

    - name: Add Ngrok to PATH
      run: echo "$env:USERPROFILE\ngrok" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

    - name: Authenticate Ngrok
      run: ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set Admin Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText $Env:RDP_PASSWORD -Force)
      env:
        RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}

    - name: Start Ngrok Tunnel
      run: ngrok.exe tcp 3389
